### ISSUE TITLE
[FIXED] Doesn't work - Unity 2021.3.9f1 (Android build)

### ISSUE THREAD

**Issue by OnyxOracle** [kiraio-moe/remove-unity-splash-screen#2]
Hi, kiraio
I tried to remove the unity splash screen in Android build, but I can't find the boolean m_ShowUnitySplashScreen. The boolean just after the first question mark after game name doesn't change anything. I noticed that you have two booleans after the first question mark(which are booleans `m_ShowUnitySplashScreen` and `m_ShowUnitySplashLogo`), but I have only one(see screenshot).
![Screenshot_1](https://user-images.githubusercontent.com/50269791/219865216-707bfe9d-fb7f-471a-87a4-b34a28ea3b11.png)

Also I tried to find `hasPROVersion` boolean, I tried to change every `00` to `01` between Scenes and Unity version, but It didn't help as well.
![Screenshot_2](https://user-images.githubusercontent.com/50269791/219865838-5fe66ea0-a6fb-4127-ade7-65d067c25abb.png)

Unity version: 2021.3.9f1
Build: Android
File: data.unity3d

**Comment by kiraio-moe** [comment]
Hi, thanks for reporting.
Can you send me the data.unity3d file?

**Comment by OnyxOracle** [comment]
Sure.
GitHub doesn't support file type, so you can download it from Google Drive.
[https://drive.google.com/file/d/1FU1EcA8wd1Hhf3oU46J86X0yuprbcjQm/view?usp=share_link](https://drive.google.com/file/d/1FU1EcA8wd1Hhf3oU46J86X0yuprbcjQm/view?usp=share_link)

**Comment by kiraio-moe** [comment]
I just added a simple way to remove Unity splash screen. You may want this alternative way: https://github.com/kiraio-moe/remove-unity-splash-screen#unity-default-resources

**Comment by kiraio-moe** [comment]
> Sure. GitHub doesn't support file type, so you can download it from Google Drive. https://drive.google.com/file/d/1FU1EcA8wd1Hhf3oU46J86X0yuprbcjQm/view?usp=share_link

Thanks, I will work on it quickly.

Edit: I can't access the file, please make it shareable.

![image](https://user-images.githubusercontent.com/58289710/219946408-cb329e72-5148-4ced-b3c3-d3d1d300cee4.png)

**Comment by OnyxOracle** [comment]
> > Sure. GitHub doesn't support file type, so you can download it from Google Drive. https://drive.google.com/file/d/1FU1EcA8wd1Hhf3oU46J86X0yuprbcjQm/view?usp=share_link
> 
> Thanks, I will work with it quickly.
> 
> Edit: I can't access the file, please make it shareable.
> 
> ![image](https://user-images.githubusercontent.com/58289710/219946408-cb329e72-5148-4ced-b3c3-d3d1d300cee4.png)

Sorry, I fixed it.

**Comment by kiraio-moe** [comment]
> Sorry, I fixed it.

Thanks.

**Comment by kiraio-moe** [comment]
Fuh~ today has discovered a new way! Will be dropped as soon as possible. Thanks for making an issue :)
Here's the modded data.unity3d file: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777425/data.unity3d.zip)
Please tell me if it work.

**Comment by OnyxOracle** [comment]
Unfortunately no. The game crashes.

https://user-images.githubusercontent.com/50269791/219965275-658ebbdb-0166-4872-9370-ca0b392b20dd.mp4

**Comment by kiraio-moe** [comment]
> Unfortunately no. The game crashes.

Hmm, give me time to resolve this. I'm using the new way to your file, so it isn't tested.

**Comment by kiraio-moe** [comment]
Here the "uncompressed" `data.unity3d` file, it's pretty big from the original file.
Give it a try: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777594/data.unity3d.zip)

Edit:
And this is `data.unity3d` file edited purely using HxD: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777648/data.unity3d.zip)

Tell me which is work.

**Comment by kiraio-moe** [comment]
What's your Compression Method while build? From what I know, if I choose Default, Unity will use `globalgamemanagers` file directly. While if I choose LZ4/LZ4HC, Unity will packing the `globalgamemanagers` file and other resources file into `data.unity3d` file. It will be more easy to remove the splash screen if you have direct access to `globalgamemanagers`.

![unity_compresssion_method](https://user-images.githubusercontent.com/58289710/219967264-67774b55-cf4a-4910-bbc2-e668ac091bbf.png)

**Comment by kiraio-moe** [comment]
> Here the "uncompressed" `data.unity3d` file, it's pretty big from the original file. Give it a try: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777594/data.unity3d.zip)
> 
> Edit: And this is `data.unity3d` file edited purely using HxD: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777648/data.unity3d.zip)
> 
> Tell me which is work.

If this is still not work, you can do it yourself so it will be more faster doing trial & error.
Use this method: https://github.com/kiraio-moe/remove-unity-splash-screen#dataunity3d

**Comment by OnyxOracle** [comment]
> Here the "uncompressed" `data.unity3d` file, it's pretty big from the original file. Give it a try: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777594/data.unity3d.zip)
> 
> Edit: And this is `data.unity3d` file edited purely using HxD: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777648/data.unity3d.zip)
> 
> Tell me which is work.

No, these two files don't work.

**But**

> What's your Compression Method while build? From what I know, if I choose Default, Unity will use `globalgamemanagers` file. While if I choose LZ4/LZ4HC, Unity will packing the `globalgamemanagers` file and other resources file into `data.unity3d` file. It will be more easy to remove the splash screen if you have direct access to `globalgamemanagers`.

This method works fine.
Thank you!

**Comment by kiraio-moe** [comment]
> > Here the "uncompressed" `data.unity3d` file, it's pretty big from the original file. Give it a try: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777594/data.unity3d.zip)
> > Edit: And this is `data.unity3d` file edited purely using HxD: [data.unity3d.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/10777648/data.unity3d.zip)
> > Tell me which is work.
> 
> No, these two files don't work.

That's sad :(

> **But**
> 
> > What's your Compression Method while build? From what I know, if I choose Default, Unity will use `globalgamemanagers` file. While if I choose LZ4/LZ4HC, Unity will packing the `globalgamemanagers` file and other resources file into `data.unity3d` file. It will be more easy to remove the splash screen if you have direct access to `globalgamemanagers`.
> 
> This method works fine. Thank you!

So finally, are you able to remove the splash screen?

**Comment by OnyxOracle** [comment]
> So finally, are you able to remove the splash screen?

Yes, I selected Default compression method and edited `globalgamemanagers` file in HxD.

**Comment by kiraio-moe** [comment]
> > So finally, are you able to remove the splash screen?
> 
> Yes, I selected Default compression method and edited `globalgamemanagers` file in HxD.

Glad to hear that :)
Case closed.
