### ISSUE TITLE
Help removing the splash screen in WebGL

### ISSUE THREAD

**Issue by nima30019** [kiraio-moe/remove-unity-splash-screen#3]
![Screenshot (69)](https://user-images.githubusercontent.com/129845173/229750126-6e4e6626-f62e-4ec2-b777-5f3b5ce0d3c8.png)
Hello, I am the one who left a comment on YouTube. Look, when I add webgl.data to hxd, I search for the company name and the project name, but I can't find anything. Can you help me?

**Comment by kiraio-moe** [comment]
Can you send me the 'salon 4.data' file?
You can do that by archiving those file to .zip then attach them in a comment.

I encourage you to read [WebGL section](https://github.com/kiraio-moe/remove-unity-splash-screen#webgl) to know more detailed instruction rather than just watching the video.

**Comment by nima30019** [comment]
Hello,

I wanted to let you know that my previous problem has been resolved. The issue was that I needed to build with the initial settings. However, in my previous project, the build file was not in zip format. When I built with the initial settings, the files were built in zip format. Unfortunately, I am now facing another problem. When I search for the Unity version, I am unable to find the string.

![image](https://user-images.githubusercontent.com/58289710/229936791-515e4d78-992b-424e-9905-1e14a58be9c3.png)

**Comment by nima30019** [comment]
![Screenshot (73)](https://user-images.githubusercontent.com/129845173/229831065-0a3746a1-6b33-407e-ba30-108d2d761b11.png)
And one more question here, you said to change 01 to 00, but here it was 00 by default.

**Comment by kiraio-moe** [comment]
> Hello,
> 
> I wanted to let you know that my previous problem has been resolved. The issue was that I needed to build with the initial settings. However, in my previous project, the build file was not in zip format. When I built with the initial settings, the files were built in zip format. Unfortunately, I am now facing another problem. When I search for the Unity version, I am unable to find the string.
> 
> ![image](https://user-images.githubusercontent.com/58289710/229936791-515e4d78-992b-424e-9905-1e14a58be9c3.png)

Ah, if you want to get the raw `globalgamemanagers` to search for `m_AuthToken`, the build must be use "Default" Compression Method in Build Settings.
See: https://github.com/kiraio-moe/remove-unity-splash-screen#notes

Hmm, seems like Unity 2023 is very different than I though 🤔 
Could you send me the `globalgamemanagers` and `webgl.data` file? (Archive them in a zip, then attach in a comment)

**Comment by kiraio-moe** [comment]
> ![Screenshot (73)](https://user-images.githubusercontent.com/129845173/229831065-0a3746a1-6b33-407e-ba30-108d2d761b11.png) And one more question here, you said to change 01 to 00, but here it was 00 by default.

IDK why, cause the WebGL is really hard to begin with. So you need to do a lot of trial and error.
I'm still wondering if there's an easy way to remove the splash screen in WebGL.

**Comment by nima30019** [comment]
this is the webgl.data and  globalgamemanagers file 
[webgl test 1.zip](https://github.com/kiraio-moe/remove-unity-splash-screen/files/11153840/webgl.test.1.zip)
thank you so much 🌹

**Comment by kiraio-moe** [comment]
Sorry for not replying for a long time. Here, checkout https://github.com/kiraio-moe/USSR
